// src/pages/CrownPage.vue
<template>
<div>
  <CrownLayout>
    <template>
      <p>A paragraph for the main content.</p>
      <p>And another one.</p>
    </template>
    <template v-slot:left>
      <h1>Here might be a page title</h1>
    </template>

    <template v-slot:right>
      <p>Here's some contact info</p>
    </template>
  </CrownLayout>
  
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import CrownLayout from "../layouts/CrownLayout";


const defaultOptions = Vue.extend({
//   props: {
//     layout: {
//       type: Object,
//       default: () => ({
//         left: {
//           width: "200px"
//         },
//         right: {
//           width: "200px"
//         }
//       })
//     }
//   }
});

@Component({
  components: {
    CrownLayout
  }
})
export default class CrownPage extends defaultOptions {
}
</script>

<style>

</style>

// src/pages/CrownPage.tsx
import { Component } from "react";
import * as React from "react";
import CrownLayout from '../layouts/CrownLayout.tsx';

export default class CrownPage extends Component<any> {
    static defaultProps = {
        layout:{
            left:{
                width:"100px"
            },
            right:{
                width:"220px"
            }
        }
    };
    constructor(props:any){
        super(props)
    }
    render() {
        const main = (<div><p>A paragraph for the main content.</p>
            <p>And another one.</p></div>);
        const left =( <h1>Here might be a page title</h1>);
        const right = (<p>Here's some contact info</p>)
        return (<CrownLayout main={main} left={left} right={right} layout={this.props.layout}>
            
        </CrownLayout>)
    }

}
