// src/pages/DualWingPage.tsx
import { Component } from "react";
import * as React from "react";
import DualWingLayout from '../layouts/DualWingLayout';

export default class DualWingPage extends Component<any> {
    constructor(props:any){
        super(props)
    }
    static defaultProps = {
        layout:{
            left:{
                width:"100px"
            },
            right:{
                width:"220px"
            }
        }
    };
    render() {
        const main = (<div><p>A paragraph for the main content.</p>
            <p>And another one.</p></div>);
        const left =( <h1>Here might be a page title</h1>);
        const right = (<p>Here's some contact info</p>)
        return (<DualWingLayout main={main} left={left} right={right} layout={this.props.layout}>
            
        </DualWingLayout>)
    }

}

// src/pages/DualWingPage.vue
<template>
  <DualWingLayout>
    <template>
      <p>A paragraph for the main content.</p>
      <p>And another one.</p>
    </template>
    <template v-slot:left>
      <h1>Here might be a page title</h1>
    </template>

    <template v-slot:right>
      <p>Here's some contact info</p>
    </template>
  </DualWingLayout>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import DualWingLayout from "../layouts/DualWingLayout";

const defaultOptions = Vue.extend({
  // props:{
  //     layout:null
  // }
  //   props: {
  //     layout: {
  //       type: Object,
  //       default: () => ({
  //         left: {
  //           width: "200px"
  //         },
  //         right: {
  //           width: "200px"
  //         }
  //       })
  //     }
  //   }
});

@Component({
  components: {
    DualWingLayout
  }
})
export default class DualWingPage extends defaultOptions {}
</script>

<style>
</style>
