// src/App.tsx
import * as React from "react";
import {
    Switch,
    Route,
    Link,
    BrowserRouter
} from "react-router-dom";
import './app.pcss'
import routes from './routes2';
import StickyFooter from "./components/StickyFooter";

export default function App() {
    const myRef = React.createRef<any>();
    return (
        <div>
            <BrowserRouter>
                <div id="router-wrapper" ref={myRef}>

                    {routes.map((route, index) => <Link key={index} to={route.path} >{route.label}</Link>)}

                    <Switch>
                        {routes.map((route, index) => <Route key={index} exact path={route.path} component={route.component} />)}
                    </Switch>
                </div>
                <StickyFooter main={myRef} children={<div>here's sticky footer</div>}></StickyFooter>
            </BrowserRouter>
        </div>

    );
}

// src/App.vue
<template>
  <div>
    <div id="app-wrapper" ref="main">
      <h1>Hello App!</h1>
      <p>
        <router-link to="/crown_page">Crown layout</router-link>
        <router-link to="/dual_wing_page">Dual Wing layout</router-link>
      </p>

      <router-view></router-view>
    </div>
    <StickyFooter :main="() => $refs.main">here's sticky footer</StickyFooter>
  </div>
</template>

<script lang="ts">
import StickyFooter from "./components/StickyFooter";
import Vue from "vue";
import Component from "vue-class-component";

const defaultOptions = Vue.extend({});
@Component({
  components: {
    StickyFooter
  }
})
export default class App extends defaultOptions {}
</script>

<style>
html * {
  margin: 0;
  padding: 0;
}
</style>
